### ISSUE TITLE
Can I add a field in default Item and default category like rating? is there any documents about customize laravel-json-api-pro

### ISSUE THREAD

**Issue by luc-hn** [creativetimofficial/ct-headless-cms-with-laravel-json-api-pro#1]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

Can I add a field in default Item and default category like rating? is there any documents about customize laravel-json-api-pro?

**Comment by teamupdivision** [comment]
Hi @luc-hn,

Thanks for using Creative Tim products. 

You may try using this method: First, use a migration to add the new field into the items table.
Then you should be able to add the custom field to the item model, to the Schema and Validators. 

Please let us know if this helped or if you need further information.

All the best

**Comment by teamupdivision** [comment]
Hi @luc-hn,

Hope this solved the problem. Please let us know if there is anything else we can help with.

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi @luc-hn ,

Hope this solved the problem. We will go ahead and close this ticket. If there is anything else we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
