### ISSUE TITLE
I need help setting this project!

### ISSUE THREAD

**Issue by abhijeets023** [creativetimofficial/ct-headless-cms-with-laravel-json-api-pro#2]
Hi,

I downloaded zip from creative-tim and when i try to run composer install
i get 72 errors saying "requires php ^7.2 but your php version (8.0.6) does not satisfy that requirement." [error.txt](https://github.com/creativetimofficial/ct-headless-cms-with-laravel-json-api-pro/files/6604076/error.txt)
how do i run this project with latest php version?

plus official laravel site says laravel 8 need PHP >= 7.3 then why this product need php 7.2??
is this build on older laravel versions?

**Comment by teamupdivision** [comment]
Hello,

We updated the download product to Laravel 8 compatibility.
Please download the product again from the Creative Tim downloads section and reinstall.
Sorry for the inconvenience.

Thank you

**Comment by abhijeets023** [comment]
how do i implement dashboard in this??
where i can add data and see users.

please help

**Comment by teamupdivision** [comment]
Hello, sorry for the late reply.
If you also want a frontend for this API you should purchase or download on of these products:
https://www.creative-tim.com/templates/vuejs-laravel-api

**Comment by teamupdivision** [comment]
Hi there @abhijeets023, 

We would like to check if the issue was solved and if there is anything else we can help with. 
Please let us know if you have any other issues. 

All the best,
Updivision Team

**Comment by teamupdivision** [comment]
Hi @abhijeets023,
 
Hope this solved the problem. We will go ahead and close this ticket. If there is anything else that can be fixed or we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
