### ISSUE TITLE
Upgrade the laravel-json-api package

### ISSUE THREAD

**Issue by vrusua** [creativetimofficial/ct-headless-cms-with-laravel-json-api-pro#3]
Hi there,

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Current Behavior

The currently used cloudcreativity/laravel-json-api package is now considered to be the legacy package by original developers.

# Expected Behavior

Could you please upgrade to the rewritten and substantially improved laravel-json-api/laravel package instead?
https://laraveljsonapi.io/docs/1.0/
https://github.com/laravel-json-api/laravel

Thank you in advance!

**Comment by teamupdivision** [comment]
Hi @vrusua,

Thanks for reporting this issue and for using Creative Tim products.

We're planning to do this upgrade in the next period of time. 

 Meanwhile, if there is anything else that can be fixed or we can help with, please let us know.
 
 Best,
 UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi @vrusua, 

We will follow up on this ticket when we'll have more updates ready.
Meanwhile, we will go ahead and close this ticket.

If there is anything else that can be fixed or we can help with, please let us know.

All the best,
UPDIVISION Team
