### ISSUE TITLE
Add Sanctum authentication support/guidelines

### ISSUE THREAD

**Issue by vrusua** [creativetimofficial/ct-headless-cms-with-laravel-json-api-pro#4]
Hi there,

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Current Behavior

Currently it is used Passport package to implement the fully pledged OAuth2 server based on the thephpleague/oauth2-server which looks cumbersome for most of SPA projects.

# Expected Behavior

Could you please add some guide how to use the Sanctum authentication instead with the "Headless CMS Laravel JSON API PRO" backend.

Thank you in advance.

**Comment by teamupdivision** [comment]
Hi @vrusua,

Thank you very much for your suggestion. It is something that we are planning to discuss and consider for future versions. 

Thank you very much. 

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi @vrusua,

We will follow up on this ticket when we'll have more updates ready. 
Meanwhile, we will go ahead and close this ticket. 

If there is anything else that can be fixed or we can help with, please let us know.

UPDIVISION Team
