### ISSUE TITLE
Getting 500 error at the MeController.php during the Guzzle patch request

### ISSUE THREAD

**Issue by vrusua** [creativetimofficial/ct-headless-cms-with-laravel-json-api-pro#5]
Hi UPDIVISION Team,

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Current Behavior

I'm getting 500 error at the MeController.php during the Guzzle patch request at this line (update profile):
```$response = $http->patch(route('api:v1:users.update', ['record' => auth()->id()]), $data);```

The read profile controller works fine. I've used the original codebase and default migrations.

# Expected Behavior

Please check over and advise how to sort out this.

Thank you!

Best,
Ruslan

**Comment by teamupdivision** [comment]
Hi Ruslan,

Thank you for reporting this issue and for using Creative Tim products. 

We're checking on this and we'll get back with a few details and additional information shortly.

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi Ruslan @vrusua,

Could you send to us a screenshot or the error message you're getting, please?  
 
All the best,
UPDIVISION Team

**Comment by vrusua** [comment]
Hi again,

this appeared when the user passed wrong credentials, in /app/Http/Controllers/Api/V1/MeController.php at the line #87
<img width="584" alt="Screenshot 2021-08-03 at 17 35 33" src="https://user-images.githubusercontent.com/2073317/128034316-192fd175-2a2c-4eff-95c7-9b16d2423273.png">

due to no ```create``` method in the ```Error``` facade, the simple fix was to replace by ```return Error::fromArray($error);```

> Could you send to us a screenshot or the error message you're getting, please?

Again it will be much easy to track amends in git if you share the repo.

Thanks,
Ruslan

**Comment by teamupdivision** [comment]
Hi Ruslan @vrusua, 

Thank you very much. We did a fix for this too and pushed together with the one for the other issue. Please let us know if this still happens and if there is anything else.

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi there @vrusua, 

We would like to check if the issue was solved and if there is anything else we can help with. 
Please let us know if you have any other issues. 

All the best,
Updivision Team

**Comment by teamupdivision** [comment]
Hi @vrusua,

Hope this solved the problem. We will go ahead and close this ticket. If there is anything else we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
