### ISSUE TITLE
Getting the routing issue

### ISSUE THREAD

**Issue by vrusua** [creativetimofficial/ct-headless-cms-with-laravel-json-api-pro#6]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Failure Information (for bugs)

** Unable to prepare route [api/v1/me] for serialization. Another route has already been assigned name [api:v1:]. **

## Steps to Reproduce

I'm getting the above LogicException in CLI trying to call
```
php artisan route:cache
``` 

## Context

Default installation, php 8

## Failure Logs

```
  at vendor/laravel/framework/src/Illuminate/Routing/AbstractRouteCollection.php:217
    213▕             $route->name($name = $this->generateRouteName());
    214▕ 
    215▕             $this->add($route);
    216▕         } elseif (! is_null($symfonyRoutes->get($name))) {
  ➜ 217▕             throw new LogicException("Unable to prepare route [{$route->uri}] for serialization. Another route has already been assigned name [{$name}].");
    218▕         }
```

**Comment by teamupdivision** [comment]
Hi Ruslan,

Thank you for reporting this issue.

We're investigating this and we'll get back with details and additional information shortly.

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi Ruslan, @vrusua 

We've pushed a fix to this problem.
You can access it by downloading the product from the downloads section in the Creative Tim website.

Please let us know if everything works well now and if there is anything else we can help with. 

All the best
UPDIVISION Team

**Comment by vrusua** [comment]
Hi there, thanks for the update! Is there any chance to track the changes in git, or? I've also sorted this a couple weeks ago and wanted to sync your amends. Thanks!

**Comment by teamupdivision** [comment]
Hi there @vrusua,

Thank you. Can you please check below? Please let us know if there is anything else that can help. 

![unknown](https://user-images.githubusercontent.com/45566836/128202200-3f04f91a-f0a3-445c-8edc-6e10e46156e7.png)

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi @vrusua,
 
Hope this solved the problem. We will go ahead and close this ticket. If there is anything else that can be fixed or we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
