### ISSUE TITLE
Expanding the API

### ISSUE THREAD

**Issue by nicklinn** [creativetimofficial/ct-headless-cms-with-laravel-json-api-pro#7]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

Omitting the remainder since this is a documentation request.   Do you have any documentation on how to expand the API to include other models?

**Comment by teamupdivision** [comment]
Hi @nicklinn,

Thank you for using the Creative Tim products.

You can find out more on this topic in the JSON:API docs here: https://laraveljsonapi.io/docs/1.0/tutorial/02-models.html.

Please let us know if you have any other questions.

Best,
UPDIVISION Team

**Comment by nicklinn** [comment]
Thank you, This is exactly what I was looking for.

**Comment by nicklinn** [comment]
Reopening because my install requires the depreciated "cloudcreativity/laravel-json-api": "^4.0", rather then "laravel-json-api/laravel" whose documentation you link to.    I cannot find a version that uses the newer api.   Where can I find it?

From: laravel-json-api-v2-master.zip
composer.json:
    "require": {
        "php": "^7.3|^8.0",
        "ext-json": "*",
        "cloudcreativity/laravel-json-api": "^4.0",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.4",
        "laravel/framework": "^9.0",
        "laravel/legacy-factories": "^1.1",
        "laravel/passport": "^10.0",
        "laravel/telescope": "^4.0",
        "laravel/tinker": "^2.6",
        "laravel/ui": "^3.0",
        "lcobucci/jwt": "^4.0.0",
        "spatie/laravel-permission": "^5.5.2"
    },
    "require-dev": {
        "cloudcreativity/json-api-testing": "^4.0",
        "fakerphp/faker": "^1.17",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^6.1",
        "nunomaduro/larastan": "^2.1.4",
        "phpunit/phpunit": "^9.5.10",
        "spatie/laravel-ignition": "^1.0"
    },

**Comment by teamupdivision** [comment]
Hi @nicklinn, the update to the new Laravel json:api package is in the works right now.
It should be ready this month. We'll keep you updated.

**Comment by nicklinn** [comment]
Following up on this.   Thank you.

**Comment by teamupdivision** [comment]
Hi @nicklinn,

Thank you very much for checking. We're close to having this ready and we think we'll be able to get back to you with great news very soon. We'll keep you posted. 

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hello @nicklinn we updated the version of the JSON:API with Laravel please download it from the product section in Creative Tim: https://www.creative-tim.com/product/headless-cms-with-laravel-json-api-pro
